name: Notify Subscribers of New Post

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get new post details
        id: post_info
        run: |
          # Get the latest post file
          LATEST_POST=$(ls -t _posts/*.md _posts/*.markdown 2>/dev/null | head -1)
          
          if [ -z "$LATEST_POST" ]; then
            echo "No posts found"
            exit 0
          fi
          
          # Extract front matter
          POST_TITLE=$(grep -m 1 "^title:" "$LATEST_POST" | sed 's/title: *//;s/"//g;s/^\[//;s/\]$//')
          POST_DATE=$(grep -m 1 "^date:" "$LATEST_POST" | sed 's/date: *//')
          POST_DESCRIPTION=$(grep -m 1 "^description:" "$LATEST_POST" | sed 's/description: *//;s/"//g')
          
          # Extract filename to build URL
          FILENAME=$(basename "$LATEST_POST")
          POST_SLUG=$(echo "$FILENAME" | sed 's/^[0-9]*-[0-9]*-[0-9]*-//;s/\.(md|markdown)$//')
          POST_YEAR=$(echo "$FILENAME" | cut -d'-' -f1)
          POST_MONTH=$(echo "$FILENAME" | cut -d'-' -f2)
          POST_DAY=$(echo "$FILENAME" | cut -d'-' -f3)
          
          # Build post URL (adjust domain as needed)
          POST_URL="https://blog.juanpaulo.xyz/$POST_YEAR/$POST_MONTH/$POST_DAY/$POST_SLUG.html"
          
          # Output for next steps
          echo "title=$POST_TITLE" >> $GITHUB_OUTPUT
          echo "date=$POST_DATE" >> $GITHUB_OUTPUT
          echo "description=$POST_DESCRIPTION" >> $GITHUB_OUTPUT
          echo "url=$POST_URL" >> $GITHUB_OUTPUT
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Check if this is a new post
        id: check_new
        run: |
          # Check if the post file was added in this commit
          git diff --name-status HEAD^ HEAD | grep "^A.*_posts/" && echo "is_new=true" >> $GITHUB_OUTPUT || echo "is_new=false" >> $GITHUB_OUTPUT

      - name: Send email via SendGrid
        if: steps.check_new.outputs.is_new == 'true'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_LIST_ID: ${{ secrets.SENDGRID_LIST_ID }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}
          POST_TITLE: ${{ steps.post_info.outputs.title }}
          POST_DESCRIPTION: ${{ steps.post_info.outputs.description }}
          POST_URL: ${{ steps.post_info.outputs.url }}
        run: |
          python3 << 'PYTHON_SCRIPT'
          import os
          import json
          import urllib.request
          import sys
          
          # Get environment variables
          api_key = os.environ['SENDGRID_API_KEY']
          list_id = os.environ['SENDGRID_LIST_ID']
          sender_email = os.environ['SENDER_EMAIL']
          sender_name = os.environ['SENDER_NAME']
          title = os.environ['POST_TITLE']
          description = os.environ['POST_DESCRIPTION']
          url = os.environ['POST_URL']
          
          # Build email content
          html_content = f"""
          <html>
          <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #333;">{title}</h1>
            <p style="color: #666; line-height: 1.6;">{description}</p>
            <p style="margin-top: 30px;">
              <a href="{url}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">Read the full post</a>
            </p>
          </body>
          </html>
          """
          
          plain_content = f"New post: {title}\n\n{description}\n\nRead more: {url}"
          
          # Create payload
          payload = {
              "name": f"New Blog Post: {title}",
              "send_to": {
                  "list_ids": [list_id]
              },
              "email_config": {
                  "subject": f"New Post: {title}",
                  "html_content": html_content,
                  "plain_content": plain_content,
                  "from": {
                      "email": sender_email,
                      "name": sender_name
                  },
                  "reply_to": {
                      "email": sender_email,
                      "name": sender_name
                  }
              },
              "send_at": "now"
          }
          
          # Send request
          url = "https://api.sendgrid.com/v3/marketing/singlesends"
          headers = {
              "Authorization": f"Bearer {api_key}",
              "Content-Type": "application/json"
          }
          
          req = urllib.request.Request(
              url,
              data=json.dumps(payload).encode('utf-8'),
              headers=headers,
              method='POST'
          )
          
          try:
              # Create the campaign
              with urllib.request.urlopen(req) as response:
                  result = json.loads(response.read().decode('utf-8'))
                  campaign_id = result.get('id')
                  print(f"✓ Email campaign created successfully!")
                  print(f"Campaign ID: {campaign_id}")
              
              # Schedule the campaign to send immediately
              schedule_url = f"https://api.sendgrid.com/v3/marketing/singlesends/{campaign_id}/schedule"
              schedule_payload = {
                  "send_at": "now"
              }
              
              schedule_req = urllib.request.Request(
                  schedule_url,
                  data=json.dumps(schedule_payload).encode('utf-8'),
                  headers=headers,
                  method='PUT'
              )
              
              with urllib.request.urlopen(schedule_req) as schedule_response:
                  print(f"✓ Campaign scheduled to send immediately!")
                  
          except urllib.error.HTTPError as e:
              error_body = e.read().decode('utf-8')
              print(f"✗ Error: {e.code} - {error_body}", file=sys.stderr)
              sys.exit(1)
          PYTHON_SCRIPT
